### ISSUE TITLE
Setting asciidoc.preview.markEditorSelection does not work

### ISSUE THREAD

**Issue by renkin-htlw5** [asciidoctor/asciidoctor-vscode#519]
## Description

As far as I understand this setting, when set to true it should work as follows:
after selecting a piece of text within editor area (within an asciidoc document), the corresponding area in preview should be visibly marked. For me it does not work in Linux and Windows - nothing happens after selection.

## System Information
VS Code:
Version: 1.64.1
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:17:47.733Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-99-generic

Extension: asciidoctor-vscode v2.9.4

## To Reproduce

Steps to reproduce the issue:

1. Open any sampleDoc.adoc in VsCode (with installed extension asciidoctor-vscode v2.9.4)
2. Open the preview
3. Double-Click any word or area
4. short time after that the corresponding piece of text should be highlighted within the preview, but nothing happens

## Screenshots & Files

none

## Additional Context

none

**Comment by Mogztter** [comment]
This attribute was copied/pasted from the Markdown extension but it seems that it's not implemented (or fully implemented).
For reference, the Markdown extension adds `data-line` attribute on all HTML elements:

```html
<p data-line="102" class="code-line" dir="auto">Docbook 5 is supported out of the box.</p>
```

When a line is selected on the text editor, it adds the CSS class `code-active-line`: https://github.com/microsoft/vscode/blob/main/extensions/markdown-language-features/preview-src/activeLineMarker.ts

The following styles are attached to this CSS class:

```css
.vscode-dark.showEditorSelection .code-active-line:before {
    border-left: 3px solid rgba(255, 255, 255, 0.4);
}

body.showEditorSelection :not(tr).code-active-line:before,
body.showEditorSelection :not(tr).code-line:hover:before {
    content: "";
    display: block;
    position: absolute;
    top: 0;
    left: -12px;
    height: 100%;
}
```

This extension is using a similar strategy regarding source map:

```html
<div class="paragraph data-line-192">
<p><em>italic phrase</em></p>
</div>
```
