### ISSUE TITLE
Custom stylesheet defined inline not working in 3.0.0-prerelease

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#598]
This is an example issue. Use just the headings and fill out all necessary information. Screenshots & Files and Additional Context are optional.

## Description

My custom stylesheet does not work in `3.0.0-prerelease`:

![image](https://user-images.githubusercontent.com/674783/177635564-599cfe91-094c-4482-a7c4-5d35066b5465.png)

When I uninstall the prerelease and switch back to the release version `2.9.8` it works:

![image](https://user-images.githubusercontent.com/674783/177635431-7b2889c1-fab4-4f83-9fb7-7e8ec6865588.png)

In each case I have the following settings:

![image](https://user-images.githubusercontent.com/674783/177635234-1f4ec5ca-054f-49dd-9e8f-791dde2cedfc.png)

## System Information

    Version: 1.68.1 (user setup)
    Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
    Date: 2022-06-14T12:48:58.283Z
    Electron: 17.4.7
    Chromium: 98.0.4758.141
    Node.js: 16.13.0
    V8: 9.8.177.13-electron.0
    OS: Windows_NT x64 10.0.19044

## To Reproduce

Steps to reproduce the issue:

1. Open a folder.
2. Create a document, something like:

    ```asciidoc
    = Test
    :stylesheet: styles.css

    Hello world

    `hey`

    What is happening?

    == Something is not right

    This is not green.
    ```

4. With a css file in the same folder, `styles.css`

    ```css
    body {
        font-family: "Times New Roman";
        color: green !important;
    }

    @media (prefers-color-scheme: dark) {
    body { background:  #333; color: white; }
    }

    @media (prefers-color-scheme: light) {
        body { background:  #ddd; color: black; }
    }

    p code {
    color: darkblue;
    }
    ```

## Screenshots & Files

See above.

## Additional Context

I think that this attribute is being overridden and that our selection logic for a custom stylesheet is incorrect.
