### ISSUE TITLE
VS Code for Windows: Unable to find Antora config file

### ISSUE THREAD

**Issue by a-bronx** [asciidoctor/asciidoctor-vscode#714]
AsciiDoc v3.0.3 preview, VS Code 1.78 for Windows

1. Created an `antora.yml` file with some asciidoc attributes:

```
name: sample
title: 'Sample'
version: '1.0'
nav:
- modules/ROOT/nav.adoc
asciidoc:
  attributes:
    # Sample attributes
    subject: 'world'
```
2. Created a sample page in a `modules/ROOT/pages`:
```
== Sample

Hello, {subject}!
```

Expected: attributes from `antora.yml` should be loaded in a Asciidoc preview and be used in Asciidoc substitutions macros (`{...}`.)
Observed: no substitution happen. The VS Code dev console shows the following message:

`[Extension Host] Unable to find an applicable Antora configuration file in [file:///c%3A/Work/Sources/sample-docs/docs/antora.yml] for the AsciiDoc document c:\Work\Sources\sample-docs\docs\modules\ROOT\pages\index.adoc.git`

Looks like an incorrect handling of Windows file paths. Probably the `match` call fails [here]( https://github.com/asciidoctor/asciidoctor-vscode/blob/fba9fb79e63c09a09e306e352ee294d8b94190d0/src/features/antora/antoraSupport.ts#LL184C5-L184C5) because of wrong type of slashes in the path.
