### ISSUE TITLE
Preview render is fixed width

### ISSUE THREAD

**Issue by itewk** [asciidoctor/asciidoctor-vscode#851]
When opening preview view the document width is fixed vs when publishing to html the document width is 100%. 

I have tried unchecking the `ASsciidoc > Preview: Use Editor Style` option but that didn't seem to change anything.

I can't tell if this is a bug or if i am missing some setting to get the preview to render the same way the HTML pubish does.

**Comment by ggrossetie** [comment]
What do you mean by the document width is 100%?

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/333276/bccbc111-6059-4a17-af14-476284b8d2b0)

Asciidoctor built-in/default style has a `max-width` with `margin: auto`.

**Comment by itewk** [comment]
im saying when i do an `asciidoc myfile.adoc` and it generates an html file, then the widith consumes the entire browser area, but the preview in the plugin, is fixed width like you have pictured.

**Comment by ggrossetie** [comment]
`asciidoc` is the legacy processor for AsciiDoc: https://asciidoc-py.github.io/
This extension is using Asciidoctor. I guess you can provide a custom CSS if you want to remove the max-width.

**Comment by itewk** [comment]
Instructions for providing the custom css somewhere?

**Comment by ggrossetie** [comment]
ℹ️ README: https://github.com/asciidoctor/asciidoctor-vscode#how-to-use

**Comment by itewk** [comment]
@ggrossetie took me a sec to figure out the settings, but got it working. thanks.

for anyone else who stumbles on this:

```css
/* import default asciidoc style sheets */
@import "https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700";
@import "https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor@2.0/data/stylesheets/asciidoctor-default.css";

/* get rid of max-width */
#header,#content,#footnotes,#footer{
    max-width:none;
}
```
